services:
  postgres_ci_cd:
    image: postgres
    container_name: postgres_ci_cd
    restart: always
    ports:
      - 1313:5432
    env_file:
      - .env.test
  

  node_ci_cd: 
    container_name: node_ci_cd
    build: .
    ports: 
    - 5000:5000 
    env_file:
      - .env.test
    depends_on:
      - postgres_ci_cd