name: Hello World 
on: [push]
jobs: 
  HelloWorld: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3 
      - run: echo "DONEEEEEEEEEEE"
      - name: List files
        run: ls ${{ github.workspace }}