name: Hello World 
on: 
  push: 
    branch: 
      - mmaster
jobs: 
  Hello-World: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3 
      - run: echo ${{secrets.MESSAGE}}
      - name: List files
        run: ls ${{ github.workspace }}