name: HelloWorld 
on: [push]

jobs: 
  HelloWorld: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
      uses: action/checkout@v3
      - name: Message 
      uses: echo DONEEEEEEEEEEE
      - name: ls ${{ github.workspace }}